# fly.toml app configuration file generated for bulma-view-components on 2024-01-02T14:35:47-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bulma-view-components"
primary_region = "sea"

[build]
  dockerfile = "demo/Dockerfile"
  ignorefile = "demo/.dockerignore"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
